spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password:
    driverClassName: org.h2.Driver
    name: FactoryDb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

  # Flyway properties
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
