spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password:
    driverClassName: org.h2.Driver
    generate-unique-name: false
    name: FactoryDb
  h2:
    console:
      enabled: true
      sql:
        init:
          mode: always
          logging:
            level:
              org.springframework.data: DEBUG
  jpa:
    hibernate:
      ddl-auto: update
