
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: ${DB_PASSWORD}
    driverClassName: org.h2.Driver
    generate-unique-name: false
    name: FactoryDb
  h2:
    console:
      enabled: true
